[package]
name = "sandstorm"
version = "0.0.5"
authors = ["David Renshaw <david@sandstorm.io>"]
license = "MIT"
description = "Sandstorm Cap'n Proto interfaces"
repository = "https://github.com/dwrensha/sandstorm-rust"
keywords = ["sandstorm"]
build = "build.rs"

[dependencies]
capnp = "0.7"

[build-dependencies]
capnpc = "0.7"