[package]
name = "sandstorm"
version = "0.0.12"
authors = ["David Renshaw <dwrenshaw@gmail.com>"]
license = "MIT"
description = "Sandstorm Cap'n Proto interfaces"
repository = "https://github.com/dwrensha/sandstorm-rust"
keywords = ["sandstorm"]
build = "build.rs"

[dependencies]
capnp = "0.12"

[build-dependencies]
capnpc = "0.12"